name: randomofo
description: randomizer for veganmofo.com
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
imports:
  crystal/authors: ~0.2.5
  crystal/bower: ~0.3.5
  crystal/express: ~0.3.2
  crystal/gitignore: ~0.1.2
  crystal/google-analytics: ~0.1.2
  crystal/license: ~0.2.4
  crystal/npm: ~0.2.5
  crystal/readme: ~0.2.2
  crystal/scraperjs: ~0.1.0
outputs:
  - generator: authors.AuthorsGenerator
    spec:
      author: $author
      name: $name
  - generator: bower.ConfigGenerator
    spec:
      directory: src/public/components
  - generator: bower.PackageGenerator
    spec:
      name: $name
      dependencies:
        jquery: 2.1.1
  - generator: express.AppGenerator
    path: src
    spec:
      body: true
      cookie:
        domain: .randomofo.com
      disable:
        - etag
      port: 3000
      routes: &routes
        home:
          uri: /
          method:
            get:
              local:
                title: "'randomofo - randomizer for veganmofo.com'"
              view: index
      static: &static
        /components: public/components
        /data: public/data
        /images: public/images
        /javascripts: public/javascripts
        /stylesheets: public/stylesheets
      title: Crystal - Open Source Code Generator for Every Language and Platform
      view:
        engine: jade
      views: src/views
  - generator: express.RouteGenerator
    path: src/routes
    spec:
      routes: *routes
  - generator: gitignore.GitignoreGenerator
    spec:
      items:
        - .DS_Store
        - node_modules/
        - src/public/components
        - npm-debug.log
  - generator: google-analytics.TrackingCodeGenerator
    filename: ga.html
    path: src/views
    spec:
      trackingID: UA-67206210-1
  - generator: license.MITGenerator
    spec:
      copyright: $copyright
  - generator: npm.PackageGenerator
    spec:
      name: randomofo
      description: randomizer for veganmofo.com
      version: 2015.0.0
      dependencies:
        body-parser: ~1.12.2
        cookie-parser: ~1.3.4
        express: ~4.8.7
        jade: ~1.9.2
        scraperjs: ~0.3.4
  - generator: readme.ReadmeGenerator
    spec:
      name: $name
      description: $description
      sections:
        - title: Install randomofo
          content: |
            1. Install [Node.js](https://nodejs.com)
            2. Install Crystal CLI: `npm install crystal-cli -g`
            3. Clone randomofo: `git clone https://github.com/ctate/randomofo`
        - title: Build randomofo
          content: |
            ```sh
            cd /path/to/ctate/randomofo
            crystal build
            ```
        - title: Run randomofo
          content: |
            ```sh
            cd /path/to/ctate/randomofo
            crystal run
            ```
  - generator: scraperjs.ScraperGenerator
    path: src
    spec:
      scrape:
        - output: src/public/data/veganmofo.json
          selector: .entry-content p a
          data:
            name: text
            url: href
      url: http://veganmofo.com/2015-blogroll
scripts:
  build:
    - bower install
    - npm update
  run:
    - node src/scraper.js
    - coffee src/app.coffee